[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
optimism = true  # Enable OP Stack features including RIP-7212 precompile at 0x100

[rpc_endpoints]
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/_3Znl6S2uNNTguhlrtMNebL72X-Hl5Fv"
